name: Build/release

on:
  workflow_dispatch:

  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Building App
        run: |
          yarn package:all

      - name: 'Zip arm64'
        run: zip -r SunsetApp-arm64.zip out/SunsetApp-darwin-arm64/SunsetApp.app

      - name: 'Zip x64'
        run: zip -r SunsetApp-x64.zip out/SunsetApp-darwin-x64/SunsetApp.app

      - name: Upload binaries to release - arm64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: SunsetApp-arm64.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload binaries to release - x64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: SunsetApp-x64.zip
          tag: ${{ github.ref }}
          overwrite: true
